### ISSUE TITLE
运行到51步，跳GPU运行内存不足。batch已经降到2了。

### ISSUE THREAD

**Issue by rain0322** [bubbliiiing/deeplabv3-plus-pytorch#57]
该如何调整，调整图片大小嘛？

**Comment by bubbliiiing** [comment]
batch降低

**Comment by t973288913** [comment]
RuntimeError: CUDA out of memory. Tried to allocate 1.25 GiB (GPU 0; 6.00 GiB total capacity; 1.09 GiB already allocated; 2.85 GiB free; 1.34 GiB reserved in total by PyTorch)
我的直接就运行不起来，
![image](https://user-images.githubusercontent.com/53886774/228125688-32f4858e-e511-4263-a691-82aa5b805db9.png)

**Comment by t973288913** [comment]
#   num_workers     用于设置是否使用多线程读取数据，1代表关闭多线程
    #                   开启后会加快数据读取速度，但是会占用更多内存
    #                   keras里开启多线程有些时候速度反而慢了许多
    #                   在IO为瓶颈的时候再开启多线程，即GPU运算速度远大于读取图片的速度。
    #------------------------------------------------------------------#
    num_workers         = 1
关闭多线程成功跑起来了

**Comment by rain0322** [comment]
> 解决了吗 @rain0322 我也是同样的问题

解决了，调小图片大小。例如我之前是932，1163左右的。统一取短边。932，932

**Comment by rain0322** [comment]
> # num_workers 用于设置是否使用多线程读取数据，1代表关闭多线程
> ```
> #                   开启后会加快数据读取速度，但是会占用更多内存
> #                   keras里开启多线程有些时候速度反而慢了许多
> #                   在IO为瓶颈的时候再开启多线程，即GPU运算速度远大于读取图片的速度。
> #------------------------------------------------------------------#
> num_workers         = 1
> ```
> 
> 关闭多线程成功跑起来了

多谢
